bootstrap/bootstrap_it/config/routes.rb
BootstrapIt::Application.routes.draw do
  resources :posts do
    resources :comments
  end
  get 'message' => 'messages#new'
  get 'about_me' => 'welcome#about_me'
  root "welcome#index"
end

bootstrap/bootstrap_it/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

bootstrap/bootstrap_it/app/models/message.rb
class Message < ActiveRecord::Base
end

bootstrap/bootstrap_it/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :title,
            presence: true,
            length: { minimum: 5 }

  def self.seed_data!
    Post.delete_all
    25.times do
      Post.create(
        :title => Faker::Lorem.sentence(rand(2..10)).chomp('.'),
        :text  => Faker::Lorem.paragraphs(rand(2..8)).join('\n')
      )
    end
  end
end

bootstrap/bootstrap_it/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bootstrap/bootstrap_it/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

bootstrap/bootstrap_it/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      # TODO send message here
      redirect_to root_url, notice: "Message sent! Thank you for contacting us."
    else
      render "new"
    end
  end
end

bootstrap/bootstrap_it/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to action: :show, id: @post.id
    else
      render 'edit'
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to action: :show, id: @post.id
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to action: :index
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

bootstrap/bootstrap_it/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about_me

  end
end

bootstrap/bootstrap_it/app/helpers/application_helper.rb
module ApplicationHelper
end

bootstrap/bootstrap_it/app/helpers/comments_helper.rb
module CommentsHelper
end

bootstrap/bootstrap_it/app/helpers/messages_helper.rb
module MessagesHelper
end

bootstrap/bootstrap_it/app/helpers/posts_helper.rb
module PostsHelper
end

bootstrap/bootstrap_it/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bootstrap/bootstrap_it/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

bootstrap/bootstrap_it/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

bootstrap/bootstrap_it/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BootstrapIt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

bootstrap/bootstrap_it/app/views/messages/new.html.erb
<h1>Contact Us</h1>
<%= link_to "Home Page", root_path %><br>

<%= form_for @message, url: message_path do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</p>

<p>
  <%= f.label :message %><br>
  <%= f.text_area :message %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

bootstrap/bootstrap_it/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

bootstrap/bootstrap_it/app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<%= link_to 'Back', action: :index %>

bootstrap/bootstrap_it/app/views/posts/index.html.erb
<h1>Steve's Tech Blog</h1>
<table>
  <tr>
    <%= link_to "Home Page", root_path %><br>
    <%= link_to 'New post', new_post_path %>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', action: :show, id: post.id %></td>
      <td><%= link_to 'Edit', action: :edit, id: post.id %></td>
      <td><%= link_to 'Destroy', { action: :destroy, id: post.id },
                      method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

bootstrap/bootstrap_it/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', action: :index %>

bootstrap/bootstrap_it/app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>

bootstrap/bootstrap_it/app/views/welcome/about_me.html.erb
<h1>About Me</h1>
<%= link_to "Home Page", root_path %>

<p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy
nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi
enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis
nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in
hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat
nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent
luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor
cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat
facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui
facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod
ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem
consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum
claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta
</p>

bootstrap/bootstrap_it/app/views/welcome/contact.html.erb
<h1>Contact Me</h1>
<%= link_to "Home Page", root_path %>

<p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy
nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi
enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis
nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in
hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat
nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent
luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor
cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat
facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui
facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod
ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem
consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum
claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta
</p>

bootstrap/bootstrap_it/app/views/welcome/index.html.erb
<h1>Steve's Portfolio Page</h1>
<%= link_to "My Blog", controller: "posts" %><br>
<%= link_to "About Me", about_me_path %><br>
<%= link_to "Contact Me", message_path %>

<div class="my_photo">
  <%= image_tag("SteveUrkel.jpg", :class => 'my_photo') %>
</div>
<p>
  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
  nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat
  volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation
  ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
  Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse
  molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero
  eros et accumsan et iusto odio dignissim qui blandit praesent luptatum
  zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor
  cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim
  placerat facer possim assum. Typi non habent claritatem insitam; est usus leg
  entis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores
  legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui
</p>

  My Projects: thisiswhyimbroke.com, associatedpress.com, instagram.com